version: "3"

silent: true

dotenv: ['.env']

vars:
  ENVIRONMENT: prod
  LOCATION: europe-west4
  PROJECT_ID: ae-dbt-ci-2025
  REPOSITORY: ae-dbt-ci-images
  TARGET_IMAGE: dbt-ci
  TAG: latest

tasks:
  env:set:
    desc: "Set environment variables from .env file downstream"
    cmds:
      - "set -a; source .env; set +a"

  tf:init:
    desc: "Terraform initialize"
    dir: infra/terraform
    cmds:
      - "terraform init"

  tf:apply:
    desc: "Terraform apply. Run this to start your infra (docker containers etc.)"
    dir: infra/terraform
    cmds:
      - "terraform apply -auto-approve"

  tf:destroy:
    desc: "Terraform destroy"
    dir: infra/terraform
    cmds:
      - "terraform destroy -auto-approve"

  gcloud:auth:
    desc: "Authenticate with Google Cloud"
    cmds:
      - echo "Authenticating with Google Cloud..."
      - gcloud auth application-default login

  docker:start:
    vars:
      BUILD: '{{.BUILD | default "false"}}'
    desc: "Start Docker containers using Docker Compose"
    cmds:
      - echo "Starting Docker containers..."
      - |
        cd infra && docker compose -f docker-compose.airflow.yml -f docker-compose.elt.yml up -d {{if eq .BUILD "true"}}--build{{end}}

  docker:start_elt:
    vars:
      BUILD: '{{.BUILD | default "false"}}'
    desc: "Start ELT Docker containers using Docker Compose"
    cmds:
      - echo "Starting ELT containers..."
      - |
        cd infra && docker compose -f docker-compose.elt.yml up -d {{if eq .BUILD "true"}}--build{{end}}


  docker:destroy:
    desc: "Destroy Docker containers using Docker Compose"
    cmds:
      - echo "Destroying Docker containers..."
      - cd infra && docker compose -f docker-compose.airflow.yml -f docker-compose.elt.yml down --volumes --remove-orphans

  docker:destroy_airflow:
    desc: "Destroy Airflow Docker containers using Docker Compose"
    cmds:
      - echo "Destroying Airflow Docker containers..."
      - cd infra && docker compose -f docker-compose.airflow.yml down --volumes --remove-orphans

  docker:destroy_elt:
    desc: "Destroy ELT Docker containers using Docker Compose"
    cmds:
      - echo "Destroying ELT Docker containers..."
      - cd infra && docker compose -f docker-compose.elt.yml down --volumes --remove-orphans

  docker:build:
      desc: "Build Docker image"
      vars:
        CURRENT_PWD:
          sh: pwd
        LOCAL_IMAGE: dbt-ci
      cmds:
        - echo "Current directory -> {{.CURRENT_PWD}}"
        - echo "Building Docker image..."
        - docker build -t {{.LOCAL_IMAGE}} .

  docker:push:
    deps:
      - docker:build
    vars:
      LOCAL_IMAGE: dbt-ci
      TARGET_IMAGE: dbt-ci
      TAGS:
        - latest
        - dockerizing
    cmds:
      - echo "Pushing Docker image to Artifact Registry..."
      - task gcloud:auth
      - gcloud auth configure-docker {{.LOCATION}}-docker.pkg.dev
      - for: { var: TAGS, as: TAG }
        cmd: docker tag {{.LOCAL_IMAGE}} {{.LOCATION}}-docker.pkg.dev/{{.PROJECT_ID}}/{{.REPOSITORY}}/{{.TARGET_IMAGE}}:{{.TAG}}
      - docker push --all-tags {{.LOCATION}}-docker.pkg.dev/{{.PROJECT_ID}}/{{.REPOSITORY}}/{{.TARGET_IMAGE}}
