goats_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{env_var('POSTGRES_HOST', 'localhost')}}"
      port: 5432
      user: "{{env_var('POSTGRES_USER', 'username')}}"
      password: "{{env_var('POSTGRES_PASSWORD', 'password')}}"
      dbname: "{{env_var('POSTGRES_DB', 'dbt')}}"
      schema: "{{env_var('DBT_DATASET', 'dbt_')}}_{{env_var('DBT_DEV_NAME', 'yourname')}}"
      threads: 4
      connect_timeout: 10
