postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: '%env:DB_HOST%'
      user: '%env:POSTGRES_USER%'
      password: '%env:POSTGRES_PASSWORD%'
      port: 5432
      dbname: '%env:DATABASE_URL%'
      schema: public
      threads: 1
