name: Docker Compose Validate

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Docker is available
        run: docker --version

      - name: Prepare env file
        run: |
          if [ -f infra/.env.example ]; then
            cp infra/.env.example .env
          fi

      - name: Validate Airflow
        run: docker compose -f infra/docker-compose.airflow.yml config

      - name: Validate ELT
        run: docker compose -f infra/docker-compose.elt.yml config
